services:
  - type: web
    name: secureprompt-ai-backend
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt && python backend/train.py"
    startCommand: "uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: firebase/firebase-key.json
